
include: package:flutter_lints/flutter.yaml

analyzer: 

  errors: 
    invalid_annotation_target: ignore

  exclude: 
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
  

linter:

  rules:
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    sort_child_properties_last: true  # Uncomment to enable the `sort_child_properties_last` rule
    prefer_const_constructors: true  # Uncomment to enable the `prefer_const_constructors` rule
    sort_constructors_first: true  # Uncomment to enable the `sort_constructors_first` rule



