name: spacex
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  rxdart: ^0.27.7

  # network
  dio: ^5.3.2
  dio_http2_adapter: ^2.3.1+1

  # dependency injection
  get_it: ^7.2.0
  injectable: ^2.3.0

  # json serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # image rendering
  cached_network_image: ^3.2.3


  # routing
  auto_route: ^7.8.3
  skeletonizer: ^0.8.0

  logger: ^2.0.2

  fpdart: ^1.1.0

  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3


  # code generation
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  freezed: ^2.4.2
  auto_route_generator: ^7.3.1

  json_serializable: ^6.7.1

  bloc_test: ^9.1.4

  mocktail: ^1.0.0
  
  http_mock_adapter: ^0.6.0


dependency_overrides: 

  # need to override this to fix conflict with bloc_test and test_api
  analyzer: ">=6.0.0 <7.0.0"

flutter:
  uses-material-design: true
